import type { Metadata } from 'next';
import { Suspense } from 'react';
import { GeneralFortuneClient } from './general-client';

export const metadata: Metadata = {
  title: 'Your Fortune Hub | Your-Fortune',
  description:
    'Choose from 10 personalised fortune categories — love, career, money, mental health, composure, exams, interviews, assignments, and golf. Get your AI-generated reading today.',
};

export default function GeneralPage() {
  return (
    <>
      {/* Static crawlable content — hidden visually, readable by search engines */}
      <section className="sr-only">
        <h1 className="text-2xl md:text-3xl font-bold text-foreground mb-3">
          Your Fortune Hub
        </h1>
        <p className="text-muted-foreground leading-relaxed mb-4">
          Welcome to Your-Fortune — your personalised daily reading across 10
          life categories. Each fortune is generated by AI based on your unique
          profile and quiz answers, delivering specific guidance, cautions, and
          opportunities tailored to this moment.
        </p>
        <div className="grid grid-cols-2 md:grid-cols-5 gap-2 mb-6">
          <div className="bg-muted/15 rounded-lg p-3 border border-border">
            <div className="text-sm font-medium text-foreground">✨ General</div>
            <div className="text-xs text-muted-foreground/60">Your overall daily reading</div>
          </div>
          <div className="bg-muted/15 rounded-lg p-3 border border-border">
            <div className="text-sm font-medium text-foreground">❤️ Love</div>
            <div className="text-xs text-muted-foreground/60">Romance and connections</div>
          </div>
          <div className="bg-muted/15 rounded-lg p-3 border border-border">
            <div className="text-sm font-medium text-foreground">💼 Career</div>
            <div className="text-xs text-muted-foreground/60">Workplace and ambition</div>
          </div>
          <div className="bg-muted/15 rounded-lg p-3 border border-border">
            <div className="text-sm font-medium text-foreground">💰 Money</div>
            <div className="text-xs text-muted-foreground/60">Financial outlook</div>
          </div>
          <div className="bg-muted/15 rounded-lg p-3 border border-border">
            <div className="text-sm font-medium text-foreground">🧠 Mental Health</div>
            <div className="text-xs text-muted-foreground/60">Wellbeing and mood</div>
          </div>
          <div className="bg-muted/15 rounded-lg p-3 border border-border">
            <div className="text-sm font-medium text-foreground">🧘 Composure</div>
            <div className="text-xs text-muted-foreground/60">Inner calm and balance</div>
          </div>
          <div className="bg-muted/15 rounded-lg p-3 border border-border">
            <div className="text-sm font-medium text-foreground">📝 Exams</div>
            <div className="text-xs text-muted-foreground/60">Test performance</div>
          </div>
          <div className="bg-muted/15 rounded-lg p-3 border border-border">
            <div className="text-sm font-medium text-foreground">🎤 Interview</div>
            <div className="text-xs text-muted-foreground/60">Preparation tips</div>
          </div>
          <div className="bg-muted/15 rounded-lg p-3 border border-border">
            <div className="text-sm font-medium text-foreground">💻 Assignment</div>
            <div className="text-xs text-muted-foreground/60">Focus and deadlines</div>
          </div>
          <div className="bg-muted/15 rounded-lg p-3 border border-border">
            <div className="text-sm font-medium text-foreground">⛳ Golf</div>
            <div className="text-xs text-muted-foreground/60">Predict your round</div>
          </div>
        </div>
        <p className="text-muted-foreground/60 text-xs mb-2">
          Select one or more categories below, then tap &ldquo;Get My Reading&rdquo; for an instant personalised fortune. Tap the gear icon on any category to customise your answers first.
        </p>
      </section>

      {/* Interactive client component */}
      <Suspense>
        <GeneralFortuneClient />
      </Suspense>
    </>
  );
}
